[package]
name = "auto-send-msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = {path = "./enigo", version = "0.0.14"}
structopt = "0.3"

[build-dependencies]
static_vcruntime = "2.0"