name: 'release'

on: workflow_dispatch


jobs:
  create-release:
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: ${version}
        id: version_check_staging
      - name: get version
        run: echo "PACKAGE_VERSION=${{steps.version_check_staging.outputs.releaseVersion}}"
#       - name: create release
#         id: create-release
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const { data } = await github.rest.repos.createRelease({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               tag_name: `app-v${process.env.PACKAGE_VERSION}`,
#               name: `Desktop App v${process.env.PACKAGE_VERSION}`,
#               body: 'Take a look at the assets to download and install this app.',
#               draft: true,
#               prerelease: false
#             })

#             return data.id
